weborder/weborder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from management import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^clear_cart/',views.clear_cart, name='clear_cart'),
    url(r'^history/order_list/$', views.order_list,name='order_list'),
    url(r'^history/', views.history, name='history'),
    url(r'^about/', views.about, name='about'),
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup,name='signup'),
    url(r'^order/$', views.order,name='order'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^setpassword/$', views.setpassword, name='set_password'),
    url(r'^add/$', views.add, name='add_instrument'),
    url(r'^add_to_cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^delete_from_cart/$', views.delete_from_cart, name='delete_from_cart'),
    url(r'^view/$', views.view, name='view_instrument'),
    url(r'^view/detail/$', views.detail, name='view_detail'),
    url(r'^image/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PATH}),
)

weborder/management/models.py
# coding :utf-8

from django.db import models
# from django.db import connection
from django.contrib.auth.models import User


class MyUser(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=16)
    permission = models.IntegerField()
    login_id = models.IntegerField(default=0)

    @staticmethod
    def get_user(username):
        if username:
            try:
                user = MyUser.objects.get(user__username=username)
            except MyUser.DoesNotExist:
                user = ''
        else:
            user = ''
        return user

    @staticmethod
    def user_logout(username):
        user = MyUser.get_user(username)
        if user:
            return user.user.is_authenticated()
        else:
            return False

    @staticmethod
    def is_already_login(username):
        try:
            user = MyUser.objects.get(user__username=username)
            if user:
                return False
                # return not user.user.is_authenticated()
            else:
                return False
        except MyUser.DoesNotExist:
            return False

    def __unicode__(self):
        return self.user.username+" "+self.nickname+" "+str(self.permission)


class Instruments(models.Model):

    name = models.CharField(max_length=128)
    price = models.FloatField(default=0.0)
    author = models.CharField(max_length=128)  # brand
    pubDate = models.DateField()
    typ = models.CharField(max_length=128)  #
    desc = models.TextField(default="")
    weight = models.FloatField(default=0)
    count = models.IntegerField(default=1)

    @staticmethod
    def get_type_list():
        book_list = Instruments.objects.all()
        type_list = set()
        for book in book_list:
            type_list.add(book.typ)
        return list(type_list)

    @staticmethod
    def check_item_id(item_id, item_count):
        if item_count > 0 and Instruments.objects.filter(pk=item_id).exists():
            return item_count <= Instruments.objects.get(pk=item_id).count
        return False

    class META:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Img(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField()
    img = models.ImageField(upload_to='image')
    item = models.ForeignKey(Instruments)

    class META:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class HomeImg(models.Model):
    name = models.CharField(max_length=128)
    type = models.CharField(max_length=128)
    img = models.ImageField(upload_to='image')
    desc = models.TextField(default="This Is Description Text")

    def __unicode__(self):
        return self.name

    class META:
        ordering = ['name']


class OrderList(models.Model):
    user = models.ForeignKey(MyUser)
    sum_price = models.FloatField()
    date = models.DateTimeField()
    weight = models.FloatField()
    address = models.CharField(max_length=128)
    transport = models.CharField(max_length=256)

    def __unicode__(self):
        return str(self.id)+" "+self.user.nickname + " $" + str(self.sum_price) + \
            " " + str(self.weight)+"Kg "+self.address + " " + self.transport


class OrderDetail(models.Model):
    order_id = models.ForeignKey(OrderList)
    item_id = models.ForeignKey(Instruments)
    count = models.IntegerField()
    price = models.FloatField()  # sold price in all
    weight = models.FloatField()  # all weight

    def __unicode__(self):
        return str(self.order_id)+" "+self.item_id.name

    class META:
        ordering = ['order_id']


class Cart(models.Model):
    user = models.ForeignKey(MyUser)
    item_id = models.ForeignKey(Instruments)
    count = models.IntegerField()
    price = models.FloatField()
    weight = models.FloatField()

    @staticmethod
    def init_user_cart(user):
        if user == '':
            return False
        else:
            Cart.objects.filter(user=user).delete()

    @staticmethod
    def get_cart_count(usr):
        if usr:
            return Cart.objects.filter(user=usr).count()
        else:
            return 0

    def __unicode__(self):
        return str(self.item_id)+" "+self.user.nickname

    class META:
        ordering = ['item_id']

weborder/management/views.py
# coding: utf-8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response
from django.template import Context, RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
# from django.http import Http404
# from django import forms
# from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from models import *


def home(req):
    user = MyUser.get_user(req.session.get('username', ''))
    content = dict(active_menu='homepage',
                   user=user, img_list=HomeImg.objects.all(),
                   cart_count=Cart.get_cart_count(user))
    return render_to_response("home.html", content)


def about(req):
    user = MyUser.get_user(req.session.get('username', ''))
    content = {'active_menu': 'about',
               'user': user,
               'cart_count': Cart.get_cart_count(user),
               }
    return render_to_response("about.html", content)


def index(req):
    user = MyUser.get_user(req.session.get('username', ''))
    content = {'active_menu': 'homepage',
               'user': user,
               'img_list': HomeImg.objects.all(),
               'cart_count': Cart.get_cart_count(user),
               }
    return render_to_response('index.html', content)


def signup(req):
    if req.session.get('username', ''):
        return HttpResponseRedirect('/')
    status = ''
    if req.POST:
        post = req.POST
        passwd = post.get('passwd', '')
        repasswd = post.get('repasswd', '')
        if passwd != repasswd:
            status = 're_err'
        else:
            username = post.get('username', '')
            if User.objects.filter(username=username):
                status = 'user_exist'
            else:
                newuser = User.objects.create_user(username=username, password=passwd, email=post.get('email', ''))
                newuser.save()
                new_myuser = MyUser(user=newuser, nickname=post.get('nickname'), permission=1)
                new_myuser.save()
                status = 'success'
    content = {'active_menu': 'homepage', 'status': status, 'user': ''}
    return render_to_response('signup.html', content, context_instance=RequestContext(req))


def login(req):
    if req.session.get('username', ''):
        return HttpResponseRedirect('/')
    next_page = req.GET.get('next', '')
    status = ''
    if req.POST:
        post = req.POST
        username = post.get('username', '')
        if MyUser.is_already_login(username):
            status = 'login_at_other_place'
        else:
            password = post.get('password', '')
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth.login(req, user)
                    req.session['username'] = username
                    Cart.init_user_cart(MyUser.get_user(username))
                    if next_page:
                        return HttpResponseRedirect(next_page)
                    return HttpResponseRedirect('/view/')
                else:
                    status = 'not_active'
            else:
                status = 'not_exist_or_password_err'
    content = {'active_menu': 'homepage', 'status': status, 'user': ''}
    return render_to_response('login.html', content, context_instance=RequestContext(req))


@login_required
def logout(req):
    auth.logout(req)
    return HttpResponseRedirect('/')


@login_required
def setpassword(req):
    user = MyUser.get_user(req.session.get('username', ''))
    if user == '':
        return HttpResponseRedirect('/login/')
    status = ''
    if req.POST:
        post = req.POST
        if user.user.check_password(post.get('old', '')):
            if post.get('new', '') == post.get('new_re', ''):
                user.user.set_password(post.get('new', ''))
                user.user.save()
                status = 'success'
            else:
                status = 're_err'
        else:
            status = 'passwd_err'
    content = {'user': user,
               'active_menu': 'user_menu',
               'status': status,
               'cart_count': Cart.get_cart_count(user),
               }
    return render_to_response('setpasswd.html', content, context_instance=RequestContext(req))


@login_required
def add(req):
    username = req.session.get('username', '')
    if username != '':
        user = MyUser.objects.get(user__username=username)
    else:
        return HttpResponseRedirect('/login/')
    if user.permission < 2:
        return HttpResponseRedirect('/')
    status = ''
    if req.POST:
        post = req.POST
        new_item = Instruments(
            name=post.get('name', ''),
            author=post.get('author', ''),
            typ=post.get('typ', ''),
            price=post.get('price', ''),
            pubDate=post.get('pubdate', ''),
        )
        new_item.save()
        status = 'success'
    content = {'user': user, 'active_menu': 'add', 'status': status}
    return render_to_response('add.html', content, context_instance=RequestContext(req))


@login_required
def history(req):
    usr = MyUser.get_user(req.session.get('username', ''))
    if usr == '':
        return login(req)
    order_lists = OrderList.objects.filter(user=usr)
    content = {'active_menu': 'history',
               'user': usr,
               'cart_count': Cart.get_cart_count(usr),
               'order_list': order_lists,
               }
    return render_to_response("history.html", content)


@login_required
def order_list(req):
    user = MyUser.get_user(req.session.get('username', ''))
    if user == '':
        return login(req)
    order_id = req.GET.get('order_id', '')
    # order_user = OrderList.objects.
    if order_id == '':
        return HttpResponseRedirect('/history/')
    have_order = False
    text = 'show_order'
    order_info = ''
    order_items = ''
    if OrderList.objects.filter(pk=order_id, user=user).exists():
        have_order = True
        order_info = OrderList.objects.get(pk=order_id)
    else:
        text = 'wrong_order_id'
    # get order details
    if have_order:
        try:
            order_items = OrderDetail.objects.filter(order_id__id=order_id)
        except OrderDetail.DoesNotExist:
            return history(req)
            # return HttpResponseRedirect('/history/')
    content = {'user': user,
               'active_menu': 'user_menu',
               'order_items': order_items,
               'order_info': order_info,
               'have_order': have_order,
               'cart_count': Cart.get_cart_count(user),
               'order_state': text,
               }
    return render_to_response('orderlist.html', content)


@login_required
def view(req):
    user = MyUser.get_user(req.session.get('username', ''))
    if user == '':
        return login(req)
    type_list = Instruments.get_type_list()
    book_type = req.GET.get('type', 'all')
    if book_type == '':
        book_lst = Instruments.objects.all()
    elif book_type not in type_list:
        book_type = 'all'
        book_lst = Instruments.objects.all()
    else:
        book_lst = Instruments.objects.filter(typ=book_type)

    if req.POST:
        post = req.POST
        keywords = post.get('keywords', '')
        book_lst = Instruments.objects.filter(name__contains=keywords)
        book_type = 'all'

    paginator = Paginator(book_lst, 5)
    page = req.GET.get('page')
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)

    content = {'user': user,
               'active_menu': 'viewpage',
               'type_list': type_list,
               'book_type': book_type,
               'book_list': book_list,
               'cart_count': Cart.get_cart_count(user),
               }
    return render_to_response('view.html', content, context_instance=RequestContext(req))


@login_required
def order(req):
    usr = MyUser.get_user(req.session.get('username', ''))
    if usr == '':
        return HttpResponseRedirect("/login/")
    arg_error = False
    text = ''
    maxnum = int(req.GET.get("maxnum", 0))
    address = req.GET.get("address", "no place")
    transport = req.GET.get("transport", "no way")
    if address == 'no place' or len(address) < 2 :
        arg_error = True
        text += ' The Address Error!'
    if transport == 'no way' or (transport != 'Air' and transport != 'Ground'):
        text += ' The Transport Means Error!'
    order_data = []
    for i in range(1, maxnum + 1):
        cart_item_id = int(req.GET.get("cart_itemid_name_" + str(i), -1))
        cart_item_amount = int(req.GET.get("cart_amount_name_" + str(i), -1))
        if cart_item_id != -1 and Instruments.check_item_id(cart_item_id, cart_item_amount):
            if not Cart.objects.filter(user=usr, item_id__id=cart_item_id).exists():
                arg_error = True
                text += ' The Item in Cart Dose Not Exist!'
                break
            order_data.append((cart_item_id, cart_item_amount))
    order_num = len(order_data)
    if order_num > 0 and not arg_error:
        new_order = OrderList.objects.create(
            user=usr,
            sum_price=0,
            weight=0,
            address=address,
            transport=transport,
            date=datetime.now(),
        )
        sum_price, sum_weight = 0.0, 0.0
        for data in order_data:
            cur_item = Instruments.objects.get(pk=data[0])
            new_detail = OrderDetail.objects.create(
                order_id=new_order,
                item_id=cur_item,
                count=data[1],
                price=cur_item.price*data[1],
                weight=cur_item.weight*data[1],
            )

weborder/management/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}About{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 well">
			<h2 class="text-center">About Us</h2>
            <h4 class="text-center">
                This Is A Course-Design Project of Software Engineer of Jilin University
            </h4>
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th>Role</th>
                    <th>Name</th>
                    <th>Stu Id</th>
                    <th>Email</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Team Leader</td>
                    <td>Kean(Hu Yaokang)</td>
                    <td>53120201</td>
                    <td>imkean@163.com</td>
                </tr>
                <tr>
                    <td>Member</td>
                    <td>Liu Qi</td>
                    <td>53120202</td>
                    <td>...</td>
                </tr>
                <tr>
                    <td>Member</td>
                    <td>Yue Hengshan</td>
                    <td>53120203</td>
                    <td>...</td>
                </tr>
                <tr>
                    <td>Member</td>
                    <td>Liu Yi</td>
                    <td>53120204</td>
                    <td>...</td>
                </tr>
                <tr>
                    <td>Member</td>
                    <td>Qiu Xuguang</td>
                    <td>...</td>
                    <td>...</td>
                </tr>
                </tbody>
            </table>
		</div>
	</div>
</div>

{% endblock %}

weborder/management/templates/add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Add Products{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">Added Successfully!</h2>
				</div>
			{% endif %}


            <form method="POST" role="form" class="form-horizontal" name="add_form">
                {% csrf_token %}
                <h1 class="form-signin-heading text-center">Add Product</h1>
				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">Name：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_name" required name="name" autofocus>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_author" class="col-md-3 control-label">Brand：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="author" id="id_author">
					</div>
				</div>

				<div class="form-group">
					<label for="id_typ" class="col-md-3 control-label">Type：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="typ" id="id_typ">
					</div>
				</div>

				<div class="form-group">
					<label for="id_price" class="col-md-3 control-label">Price：</label>
					<div class="col-md-9">
						<input type="text" class="form-control"  required name="price" id="id_price" onkeyup="check()">
					</div>
				</div>

				<div class="form-group">
					<label for="id_pubdate" class="col-md-3 control-label">Date：</label>
					<div class="col-md-9">
						<input type="date" class="form-control" required name="pubdate" id="id_pubdate">
					</div>
				</div>
                <script>
                    function check()
                    {
                        var x=document.getElementById("id_price");
                        if(!$.isNumeric(x.value))
                        {
                            //alert("Not A Number");
                            x.value = '';
                            return false;
                        }
                        return true;
                    }
                </script>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-4">
                        <button class="btn btn btn-primary btn-block" type="submit" onsubmit="return check()">Submit</button>
                    </div>
                </div>
            </form>
        </div>
	</div>
</div>


{% endblock %}

weborder/management/templates/addbook.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">添加成功</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">添加图书</h1>

				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">书名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_name" required name="name" autofocus>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_author" class="col-md-3 control-label">作者：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="author" id="id_author">
					</div>
				</div>

				<div class="form-group">
					<label for="id_typ" class="col-md-3 control-label">类型：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="typ" id="id_typ">
					</div>
				</div>

				<div class="form-group">
					<label for="id_price" class="col-md-3 control-label">价格：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="price" id="id_price">
					</div>
				</div>

				<div class="form-group">
					<label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
					<div class="col-md-9">
						<input type="date" class="form-control" required name="pubdate" id="id_pubdate">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock %}

weborder/management/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{%  static "img/icon.ico" %}">
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-theme.min.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
		<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>

		<!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!--Here is the navbar-->
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
                      <li id="homepage"><a href="{% url 'index' %}" class="navbar-brand">
                            <span class="glyphicon glyphicon-home"></span>&nbsp;Web Order</a>
                      </li>
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-basepage">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="navbar-collapse-basepage">
					<ul class="nav navbar-nav">

						<li id="viewpage"><a href="{% url 'view_instrument' %}">
                            <span class="glyphicon glyphicon-list"></span>&nbsp;Browse Catalog</a>
                        </li>

					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if user %}
                            <li id="cart"><a href="{% url 'cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Cart&nbsp;<span class="badge">{{ cart_count }}</span></a></li>
                            <li id="history"> <a href="{% url 'history' %}"><span class="glyphicon glyphicon-tasks"></span>&nbsp;History</a></li>
                            <li class="dropdown" id="user_menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <span class="glyphicon glyphicon-user"></span>&nbsp;{{ user.nickname }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">

                                    <li class="divider"></li>
                                    <li><a href="{%  url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Sign Out</a></li>
                                    <li><a href="{% url 'set_password' %}"><span class="glyphicon glyphicon-lock"></span>&nbsp;Set Password</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-registration-mark"></span>&nbsp;Register</a></li>
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Sign In</a></li>
                        {% endif %}
                        <li id="about"><a href="{% url 'about' %}">
                            <span class="glyphicon glyphicon-info-sign"></span>&nbsp;About</a>
                        </li>
                    </ul>
                </div>
			</div>
		</nav>
		<!-- /nav -->
		<!-- header -->
		<header class="jumbotron subhead" id="header-base" >
			<div class="container" >
				<h1>Web Order</h1>
				<h2>&emsp;&emsp;The Best Web to Get Your Lovely Instruments , Music Starts Here !</h2>
			</div>
		</header>
		<!-- /.header -->
		<!-- main part -->
		{% block content %}{% endblock %}
		<!-- /.main -->
	
		<!-- footer -->
        <br/><br/>
		<footer class="footer" role="contentinfo">
			<hr>
			<div class="container">
				<p class="text-center"><strong>CCST-JLU</strong></p>
				<p class="text-center">©All rights reserved</p>
				<h5 class="text-center"> Powered by&nbsp;<a href="https:github.com/hikean">Kean</a></h5>
			</div>
		</footer>
		<!-- /.footer-->
		<script type="text/javascript">
		    var act = document.getElementById("{{ active_menu }}");
		    act.setAttribute("class","active");
		</script>
	</body>
</html>

weborder/management/templates/history.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}History Lists{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 well">
			<h2 class="text-center">History Order Lists</h2>

            <table class="table table-hover  table-bordered">
					<thead>
						<tr>
							<th>No.</th>
                            <th>Order ID</th>
							<th>Price($)</th>
							<th>weight(Kg)</th>
							<th>Date Time</th>
							<th>Address</th>
                            <th>Transport</th>
						</tr>
					</thead>
					<tbody>
						{% for order in order_list %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td><a href="{% url 'order_list' %}?order_id={{order.id}}">{{ order.id }}</a></td>
							<td>{{ order.sum_price|floatformat:2 }}</td>
							<td>{{ order.weight|floatformat:2}}</td>
							<td>{{ order.date |date:"Y/m/d/H:i:s"}}</td>
							<td>{{ order.address}}</td>
							<td>{{ order.transport}}</td>
						</tr>
                        {% endfor %}
                    </tbody>
            </table>
            {% if order_list.count == 0 %}
                <h3>No Order List at Present!</h3>
            {% endif %}
            <br/> <br/> <hr/>
            <h4 class="text-center">Email:<span  class="text-info">imkean@163.com</span></h4>
            <p class="text-center">
                This Is A Course-Design Project of Software Engineer of Jilin University
            </p>
        </div>
    </div>
</div>

{% endblock %}

weborder/management/templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Register{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
            {% if status == 'success' %}
                <div class="well">
                    <h2 class="text-success text-center">Register Successfully！</h2>
                </div>
            {% elif status == 're_err' %}
                <div class="well">
                    <h2 class="text-warning text-center">Passwords Didn't Match  </h2>
                </div>
            {% elif status == 'user_exist' %}
                <div class="well">
                    <h2 class="text-danger text-center">User Already Exists!</h2>
                </div>
            {% endif %}
            <form method="POST" role="form" class="form-horizontal">
                {% csrf_token %}
                <h1 class="form-signin-heading text-center">Sign Up</h1>
                <br/>
                <div class="form-group">
                    <label for="id_user_name" class="col-md-4 control-label">User Name:</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
                        <span class="help-block">For  Login  including alpha ,digit and underline char</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_name" class="col-md-4 control-label">Nickname:</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" required name="nickname" id="id_name">
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_passwd" class="col-md-4 control-label">Password:</label>
                    <div class="col-md-8">
                        <input type="password" class="form-control" required name="passwd" id="id_passwd">
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_repasswd" class="col-md-4 control-label"> Repassword:</label>
                    <div class="col-md-8">
                        <input type="password" class="form-control" required name="repasswd" id="id_repasswd">
                    </div>
                </div>
				
                <div class="form-group">
                    <label for="id_email" class="col-md-4 control-label">E-mail:</label>
                    <div class="col-md-8">
                        <input type="email" class="form-control" required name="email" id="id_email">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button class="btn btn-success  btn-block" type="submit" id="id_submit">Register Now!</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}